LAB_NAME="VULN_BOX"
LAB_DESCRIPTION="Lab de réseau local pour exploitation de machines et test de sécurité"
LAB_AUTHOR="sp1der"
LAB_EMAIL="amosakogbe@gmail.com"

# Terminals
# PCs
linux1[num_terms]=1
pc2[num_terms]=0
server[num_terms]=1
webserver[num_terms]=1
tomcat[num_terms]=1

# Routers
r1[num_terms]=1

# Define devices in first zone
linux1[0]="A"
r1[2]="A"
pc2[0]="A"
server[0]="A"

# Define devices in extranet zone
r1[1]="B"
webserver[0]="B"

# Define DMZ zone
r1[0]="D"
tomcat[0]="D"

# Tomcat (using tomcat image)
tomcat[image]="tomcat"

#Linux1 & webserver (running ubuntu)
linux1[image]="asgard-server"
webserver[image]="ubuntu-server"

#server (running openvas)
server[image]="kathara-kali"
#port redirection
server[port]="9392:9392/tcp"


# extranet
webserver[bridged]=true
server[bridged]=true
linux1[bridged]=true
tomcat[bridged]=true
webserver[port]="8080:80/tcp"
