# Emplacement du répertoire d'accueil des utilisateurs
local_root=/home/ftp

# Activer ou désactiver l'accès FTP anonyme
anonymous_enable=YES

# Activer l'accès FTP pour les utilisateurs locaux
local_enable=YES

# Activer la permission d'écriture pour les utilisateurs locaux
write_enable=YES

# Activer les messages à l'entrée et à la sortie des répertoires
dirmessage_enable=YES

# Enregistrement des transferts FTP
xferlog_enable=YES

# Définir le format du fichier de log des transferts
xferlog_std_format=YES

# Activer les configurations chroot pour les utilisateurs locaux
chroot_local_user=YES

# Spécifier la bannière de bienvenue
ftpd_banner=Your FTP is shinning !!!!!! and running  ASAP .

# Paramètres de performance
idle_session_timeout=600
data_connection_timeout=120

# Activer le mode passif et définir la plage de ports passifs
pasv_enable=YES
pasv_min_port=10000
pasv_max_port=10100

# Définir les droits d'accès aux fichiers créés
local_umask=022

# Activer SSL pour les connexions sécurisées
ssl_enable=YES

# Autres options de sécurité
pam_service_name=vsftpd
userlist_enable=NO
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO
